{"name": "test_registration[firefox]", "status": "broken", "statusDetails": {"message": "TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'", "trace": "browser_name = 'firefox'\n\n    @allure.feature('Registration')\n    @allure.story('User can register with valid details')\n    @pytest.mark.parametrize(\"browser_name\", [\"chrome\", \"firefox\"])\n    def test_registration(browser_name):\n>       driver = DriverFactory.get_driver(browser_name)\n\ntests\\test_registration.py:19: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nbrowser_name = 'firefox'\n\n    @staticmethod\n    def get_driver(browser_name=\"chrome\"):\n        if browser_name == \"chrome\":\n            driver = webdriver.Chrome(ChromeDriverManager().install())\n        elif browser_name == \"firefox\":\n>           driver = webdriver.Firefox(executable_path=GeckoDriverManager().install())\nE           TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'\n\ndrivers\\driver_factory.py:12: TypeError"}, "parameters": [{"name": "browser_name", "value": "'firefox'"}], "start": 1723650186463, "stop": 1723650188603, "uuid": "59000e18-ac6e-435b-94e3-ed8f62e362d1", "historyId": "dcc3e78ff4c001f2a2268da5a2eada65", "testCaseId": "c205956376af689025d4869fba865b9d", "fullName": "tests.test_registration#test_registration", "labels": [{"name": "feature", "value": "Registration"}, {"name": "story", "value": "User can register with valid details"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_registration"}, {"name": "host", "value": "DESKTOP-5O9S9MI"}, {"name": "thread", "value": "17544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_registration"}]}